POST http://localhost:3007/register
Content-Type:application/json

{
  "username": "adam_richar",
  "name": "Adam Richard",
  "password": "richard_567",
  "gender": "male",
  "location": "Detroit"
}

### API 1

POST http://localhost:3007/login
Content-Type: application/json

{
  "username": "adam_richar",
  "password": "richard_567"
}
